version: "3.7"

services:
  #Overseerr
  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    restart: unless-stopped
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Africa/Johannesburg
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/overseerr:/config