---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /docker/appdata/plex:/config
      - /tmp/plex:/transcode
      - /data/media:/data/media
    restart: unless-stopped
