version: "3.7"

services:
  plex:
    container_name: plex
    image: ghcr.io/hotio/plex
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Africa/Johannesburg
      - PLEX_CLAIM_TOKEN=claim-8Xs-m7aCZ4vgiEW7naCq
      - PLEX_ADVERTISE_URL
      - PLEX_NO_AUTH_NETWORKS=192.168.0.116
      - PLEX_BETA_INSTALL=false
    volumes:
      - /docker/appdata/plex:/config
      - /tmp/plex:/transcode
      - /data/media:/data/media
